language: node_js
node_js:
  - "7"
jobs:
  include:
    - stage: unit tests
      script: "npm test"
    - stage: deploy to staging
      script: skip
      deploy: &heroku
        provider: heroku
        app: fsm-engine-restful
        api_key: 246542ac-8051-4867-aa1b-89abe4fb5dc9
#    - stage: test staging
#      script: 'curl http://fsm-engine-restful-staging.herokuapp.com'
    - stage: deploy to production
      script: skip
      deploy:
        <<: *heroku
        app: fsm-engine-restful
    - stage: test production
      script: 'curl http://fsm-engine-restful.herokuapp.com'
